services:
  # Application PHP
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: ecoride_app
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www/html
    networks:
      - ecoride_net

    # env_file seulement si le fichier existe (dev local)
    env_file:
      - ../.env

    environment:
      # Mode avec Supabase
      APP_ENV: ${APP_ENV:-docker_development}

      # Variables Mailjet - Fonctionnent dans les deux cas :
      # - Dev local : chargées depuis .env
      # - Prod Fly : injectées par fly secrets
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}
      MAILJET_FROM_EMAIL: ${MAILJET_FROM_EMAIL}
      MAILJET_FROM_NAME: ${MAILJET_FROM_NAME}

      # Alternative: Mode avec DB locale
      # Décommenter les lignes et commenter DATABASE_URL pour utiliser la DB locale
      # DB_HOST: db
      # DB_PORT: 5432
      # DB_NAME: ecoride_dev
      # DB_USER: postgres
      # DB_PASSWORD: password123

networks:
  ecoride_net: