services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: ecoride_app
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www/html
    networks:
      - ecoride_net
    env_file:
      - ../.env

volumes:
  db_data:

networks:
  ecoride_net: