services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: ecoride_app
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www/html
      # Exclure node_modules pour éviter les conflits
      - /var/www/html/node_modules
    networks:
      - ecoride_net
    env_file:
      - ../.env
    # Commande pour rebuilder les JS en dev si nécessaire
    # command: sh -c "npm run build && apache2-foreground"

  # Service optionnel pour watcher les changements JS en dev
  js-watcher:
    build:
      context: ../
      dockerfile: Dockerfile.dev  # Voir ci-dessous
    container_name: ecoride_js_watcher
    volumes:
      - ../:/app
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    networks:
      - ecoride_net

volumes:
  db_data:

networks:
  ecoride_net: